# Required metadata
sonar.projectKey=VedantB-sudo_LeasePro-Cloud
sonar.projectName=LeasePro-Cloud
sonar.projectVersion=1.0

# Path to source folders
sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/tests.py,**/migrations/**,manage.py,venv/**,static/**,media/**