name: Static Analysis Pylint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: ./LeasePro-Cloud
        run: |
          python -m pip install --upgrade pip
          pip install pylint pylint-django
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Pylint
        working-directory: ./LeasePro-Cloud
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pylint --load-plugins pylint_django --django-settings-module=LeasePro-Cloud.settings . --exit-zero